### ISSUE TITLE
Migrate stacks to k8s for cloud deployments

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#111]
Need to create k8s definitions for:
 - [x] PSI and OneStop as done in #106 and #112
- [x] Other currently defined stacks , e.g. common ingest

**Comment by mcquinne** [comment]
We decided that our deployment definitions should be separate from the development definitions inside each repo and that we should take a look at using helm to manage them.

To that end, I created a repo to build helm charts in here: https://github.com/cedardevs/helm-charts

**Comment by StrayCat1** [comment]
Migrating Common-Ingest

**Comment by StrayCat1** [comment]
Everything works locally. 

Seeing what changes would be necessary to deploy to GKE. 

Should I create a helm chart  common-ingest or is that overkill?

**Comment by StrayCat1** [comment]
It appears you cant have a GCE volume with `accessMode: ReadWriteMany`.

Given this StorageClass and PVC:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ingest-data-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-central1-a
  replication-type: none

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-pvc
spec:
  storageClassName: ingest-data-storage
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
```

I get this error when deploying to GKE- 

```
$ kubectl describe pvc ingest-pvc
Name:          ingest-pvc
Namespace:     default
StorageClass:  ingest-data-storage
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"ingest-pvc","namespace":"default"},"spec":{"accessModes":["ReadW...
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  14s (x21 over 5m)  persistentvolume-controller  Failed to provision volume with StorageClass "ingest-data-storage": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported
```
