### ISSUE TITLE
Deploy FaaS System

### ISSUE THREAD

**Issue by ajakz** [cedardevs/psi#144]
Goal:
Kubernetes cluster has architecture to support serverless functions.

AC:
- [ ] Local deployment (minikube environment)
- [ ] Sciapps deployment
- [ ] Cloud deployment

**Comment by StrayCat1** [comment]
Modified the official apache openwhisk kube deploy project so we can deploy their chart to our cluster where kafka and zookeeper are already defined. 
Here is the fork with those changes
https://github.com/cedardevs/incubator-openwhisk-deploy-kube
Spoke with the OW team on slack, they requested we contribute what we did. Made a pull request- https://github.com/apache/incubator-openwhisk-deploy-kube/pull/257

We should be ready to deploy this to CU when the VMs are ready. 

In the meantime, think Ill deploy it to a GKE cluster.

**Comment by StrayCat1** [comment]
To deploy openwhisk locally
- follow the guide [here](https://github.com/apache/incubator-openwhisk-deploy-kube) 
- see the example `mycluster.yaml` below
- configure your wsk cli with the external ip of your local k8s node

```yaml
---
whisk:
  ingress:
    type: NodePort
    tls:
      enabled: false
    api_host_name: <internal ip>
    api_host_port: 31001

nginx:
  httpsNodePort: 31001
```



Relevant links-
https://github.com/apache/incubator-openwhisk
https://github.com/apache/incubator-openwhisk-deploy-kube
https://github.com/apache/incubator-openwhisk-package-kafka
https://github.com/daisy-ycguo/openwhisk-deploy-kube-packages
