### ISSUE TITLE
Metadata-scraper hits sciapps psi basic auth endpoint

### ISSUE THREAD

**Issue by cEsterlein** [cedardevs/psi#56]
The PSI API (just the one endpoint) is hosted at  sciapps.colorado.edu/psi/metadata/granule and uses http basic auth. We need to update metadata-scraper so it can send credentials for basic auth.

**Comment by cEsterlein** [comment]
Updating metadata scraper to make use of  credentials. Reorganized the config params just a bit- 
```
rabbitmq:
  connectionfactory:
    password: <pw>
    virtualHost: <virtualHost>
    username: <username>
    host: <host>


logging:
  file: ${HOME}/logs/metadata-scraper.log
  level:
    root: DEBUG

metadata:
  client:
    url: <url>
    username: <username>
    password: <pw>
```
