### ISSUE TITLE
Add filter config to script-wrapper

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#75]
Goal: Only run the given script on a subset of incoming messages

Strawman:

```yml
filter:
  key: 'datastream'
  pattern: 'dscovr'
```
